spring:
  application:
    name: msclient

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log


eureka:
  client:
    service-url:
      defaultZone: http://erika:erika03@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

